export interface MedicationData {
    productName: string;
    activeIngredient: string;
}

/**
 * Uma lista selecionada de medicamentos com seus princípios ativos correspondentes,
 * baseada em dados públicos da ANVISA. Esta lista é usada para fornecer exemplos
 * ao modelo de IA, melhorando a precisão e relevância das prescrições geradas.
 *
 * A lista foi processada para remover duplicatas, entradas sem um princípio ativo
 * válido (DCB - Denominação Comum Brasileira), ordenada alfabeticamente e corrigida.
 */
export const medications: MedicationData[] = [
    { productName: "A SAÚDE DA MULHER", activeIngredient: "EXTRATO FLUIDO DE CASCA DE LARANJA AMARGA + EXTRATO FLUIDO DE PASSIFLORA ALATA + SALICILATO DE SÓDIO + TINTURA AGONIADA PLUMÉRIA" },
    { productName: "AAS", activeIngredient: "ACIDO ACETILSALICILICO" },
    { productName: "AAS PROTECT", activeIngredient: "ÁCIDO ACETILSALICÍLICO" },
    { productName: "ABBA", activeIngredient: "ACETATO DE ABIRATERONA" },
    { productName: "ABC", activeIngredient: "CLOTRIMAZOL" },
    { productName: "ABCLER ABNAT", activeIngredient: "BETAÍNA + CITRATO DE COLINA + DL-METIONINA + LEVOMETIONINA" },
    { productName: "ABERALGINA", activeIngredient: "DIPIRONA" },
    { productName: "ABLOK", activeIngredient: "ATENOLOL" },
    { productName: "ABLOK PLUS", activeIngredient: "ATENOLOL + CLORTALIDONA" },
    { productName: "ABRETIA", activeIngredient: "CLORIDRATO DE DULOXETINA" },
    { productName: "ABRIFIT", activeIngredient: "HEDERA HELIX L." },
    { productName: "ABRILAR", activeIngredient: "HEDERA HELIX L." },
    { productName: "ABRYSVO", activeIngredient: "VACINA VÍRUS SINCICIAL RESPIRATÓRIO A E B (RECOMBINANTE)" },
    { productName: "ACALMILFITO", activeIngredient: "CRATAEGUS RHIPIDOPHYLLA GAND. + PASSIFLORA INCARNATA L. + VALERIANA OFFICINALIS L." },
    { productName: "ACCLAF", activeIngredient: "AMOXICILINA TRI-HIDRATADA + CLAVULANATO DE POTÁSSIO" },
    { productName: "ACCOLATE", activeIngredient: "ZAFIRLUKAST" },
    { productName: "ACCUPRIL", activeIngredient: "QUINAPRIL" },
    { productName: "ACCUVIT", activeIngredient: "ACETATO DE RACEALFATOCOFEROL + BETACAROTENO + OXIDO CUPRICO + RIBOFLAVINA + SELENATO DE SÓDIO + ÁCIDO ASCÓRBICO + ÓXIDO CÚPRICO + ÓXIDO DE ZINCO" },
    { productName: "ACEBROFILINA", activeIngredient: "ACEBROFILINA" },
    { productName: "ACECLOFENACO", activeIngredient: "ACECLOFENACO" },
    { productName: "ACEFLOR", activeIngredient: "ACECLOFENACO" },
    { productName: "ACERATUM", activeIngredient: "PERÓXIDO DE URÉIA" },
    { productName: "ACHEFLAN", activeIngredient: "CORDIA VERBENACEA DC." },
    { productName: "ACLAF", activeIngredient: "AMOXICILINA TRI-HIDRATADA + CLAVULANATO DE POTÁSSIO" },
    { productName: "ACLASTA", activeIngredient: "ÁCIDO ZOLEDRÔNICO MONOIDRATADO" },
    { productName: "ACFOL", activeIngredient: "ÁCIDO FÓLICO" },
    { productName: "ACZEO", activeIngredient: "ÁCIDO AZELAICO" },
    { productName: "AD FURP", activeIngredient: "COLECALCIFEROL + PALMITATO DE RETINOL + ÓXIDO DE ZINCO" },
    { productName: "AD TIL", activeIngredient: "POLIVITAMINAS SEM MINERAIS" },
    { productName: "ADDERA D3", activeIngredient: "COLECALCIFEROL" },
    { productName: "ADDITIVA VITAMINA C", activeIngredient: "ÁCIDO ASCÓRBICO" },
    { productName: "ADEKS", activeIngredient: "POLIVITAMINICOS COM MINERAIS" },
    { productName: "ADERA D3", activeIngredient: "COLECALCIFEROL" },
    { productName: "adenosina", activeIngredient: "ADENOSINA" },
    { productName: "ADVIL", activeIngredient: "IBUPROFENO" },
    { productName: "aero-ifal", activeIngredient: "SULFATO DE SALBUTAMOL" },
    { productName: "AFECSO", activeIngredient: "CLORIDRATO DE FEXOFENADINA" },
    { productName: "AFETUS", activeIngredient: "CLORIDRATO DE SERTRALINA" },
    { productName: "agomelatina", activeIngredient: "AGOMELATINA" },
    { productName: "Air Salonpas", activeIngredient: "LEVOMENTOL + CÂNFORA + SALICILATO DE METILA + SALICILATO DE ETILENOGLICOL" },
    { productName: "Alginac", activeIngredient: "CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA + DICLOFENACO DE SÓDIO + DICLOFENACO SÓDICO + NITRATO DE TIAMINA" },
    { productName: "ALLEGRA", activeIngredient: "CLORIDRATO de FEXOFENADINA" },
    { productName: "Alprazolam", activeIngredient: "ALPRAZOLAM" },
    { productName: "AMATO", activeIngredient: "TOPIRAMATO" },
    { productName: "Aminoven 10% Infant", activeIngredient: "ACETATO DE LISINA + ACETILCISTEÍNA + ACETILTIROSINA + ALANINA + ARGININA + FENILALANINA + GLICINA + HISTIDINA + ISOLEUCINA + L-METIONINA + LEUCINA + LEVOVALINA + PROLINA + SERINA + TAURINA + TREONINA + TRIPTOFANO + ÁCIDO MÁLICO" },
    { productName: "AMINOVEN", activeIngredient: "ACETATO DE LISINA + ALANINA + ARGININA + FENILALANINA + GLICINA + HISTIDINA + ISOLEUCINA + L-ALANINA + L-FENILALANINA + L-HISTIDINA + L-ISOLEUCINA + L-LEUCINA + L-METIONINA + L-PROLINA + L-SERINA + L-TREONINA + L-TRIPTOFANO + LEUCINA + LEVOVALINA + PROLINA + SERINA + TAURINA + TIROSINA + TREONINA + TRIPTOFANO" },
    { productName: "Amytril", activeIngredient: "CLORIDRATO DE AMITRIPTILINA" },
    { productName: "Amoxicilina", activeIngredient: "AMOXICILINA TRI-HIDRATADA" },
    { productName: "ANAFRANIL", activeIngredient: "CLORIDRATO DE CLOMIPRAMINA" },
    { productName: "Anlodipino", activeIngredient: "BESILATO DE ANLODIPINO" },
    { productName: "ANSIODORON", activeIngredient: "AVENA SATIVA L. + PASSIFLORA ALATA CURTIS + VALERIANA OFFICINALIS L." },
    { productName: "ANSIOLEX", activeIngredient: "BROMAZEPAM" },
    { productName: "apixabana", activeIngredient: "APIXABANA" },
    { productName: "ARGEVIT C", activeIngredient: "ASPARTATO DE ARGININA + ÁCIDO ASCÓRBICO" },
    { productName: "ASPIRINA PREVENT", activeIngredient: "ÁCIDO ACETILSALICÍLICO" },
    { productName: "ATAK CLAV", activeIngredient: "AMOXICILINA TRI-HIDRATADA + CLAVULANATO DE POTÁSSIO" },
    { productName: "ATELIDONA", activeIngredient: "ATENOLOL + CLORTALIDONA" },
    { productName: "ATELOP", activeIngredient: "BESILATO DE LEVANLODIPINO" },
    { productName: "AYMEN", activeIngredient: "AMOXICILINA TRI-HIDRATADA + CLAVULANATO DE POTÁSSIO" },
    { productName: "AZELAN", activeIngredient: "ÁCIDO AZELAICO" },
    { productName: "Azitromicina", activeIngredient: "AZITROMICINA DI-HIDRATADA" },
    { productName: "BENICAR OD", activeIngredient: "OLMESARTANA MEDOXOMILA" },
    { productName: "BONVIVA", activeIngredient: "IBANDRONATO DE SÓDIO MONOIDRATADO" },
    { productName: "CADVAS", activeIngredient: "MESILATO DE DOXAZOSINA" },
    { productName: "Carbolitium", activeIngredient: "CARBONATO DE LÍTIO" },
    { productName: "CEBETYM", activeIngredient: "CETOCONAZOL + DIPROPIONATO DE BETAMETASONA + SULFATO DE NEOMICINA" },
    { productName: "CEDUR", activeIngredient: "BEZAFIBRATO" },
    { productName: "Ciprofloxacino", activeIngredient: "CLORIDRATO DE CIPROFLOXACINO" },
    { productName: "CIRCUIT", activeIngredient: "MIRABEGRON" },
    { productName: "Citalor", activeIngredient: "ATORVASTATINA CÁLCICA" },
    { productName: "CLINBACTER", activeIngredient: "CLARITROMICINA" },
    { productName: "CLORETO DE SÓDIO", activeIngredient: "CLORETO DE SÓDIO" },
    { productName: "cloridrato de tramadol + diclofenaco sódico", activeIngredient: "CLORIDRATO DE TRAMADOL + DICLOFENACO SÓDICO" },
    { productName: "COLÍRIO TEUTO", activeIngredient: "CLORIDRATO DE NAFAZOLINA + SULFATO DE ZINCO" },
    { productName: "Coreg", activeIngredient: "CARVEDILOL" },
    { productName: "Crestor", activeIngredient: "ROSUVASTATINA CÁLCICA" },
    { productName: "CUTISANOL", activeIngredient: "IODETO DE TIMOL + OXIDO DE ZINCO + SUBGALATO DE BISMUTO" },
    { productName: "Cymbalta", activeIngredient: "CLORIDRATO DE DULOXETINA" },
    { productName: "DAFLON", activeIngredient: "DIOSMINA + FLAVONÓIDES EXPRESSOS EM HESPERIDINA + HESPERIDINA" },
    { productName: "DAFORIN", activeIngredient: "CLORIDRATO DE FLUOXETINA" },
    { productName: "DAGLI", activeIngredient: "GLICLAZIDA" },
    { productName: "DECONLERG", activeIngredient: "DESLORATADINA" },
    { productName: "DENBONLI", activeIngredient: "DENOSUMABE" },
    { productName: "DEPANTEX", activeIngredient: "DEXPANTENOL" },
    { productName: "DEPAKOTE", activeIngredient: "DIVALPROATO DE SÓDIO" },
    { productName: "Depakene", activeIngredient: "ÁCIDO VALPROICO" },
    { productName: "DESLANOL", activeIngredient: "DESLANOSÍDEO" },
    { productName: "DESLIN", activeIngredient: "DESLORATADINA" },
    { productName: "DETRUSITOL", activeIngredient: "TARTARATO DE TOLTERODINA" },
    { productName: "DEXADOR", activeIngredient: "CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA + FOSFATO DE DEXAMETASONA + NITRATO DE TIAMINA" },
    { productName: "Diazepam", activeIngredient: "DIAZEPAM" },
    { productName: "DOBU", activeIngredient: "CLORIDRATO DE DOBUTAMINA" },
    { productName: "DONEX", activeIngredient: "CLORIDRATO DE TRAZODONA" },
    { productName: "Donaren", activeIngredient: "CLORIDRATO DE TRAZODONA" },
    { productName: "DORFLEX UNO", activeIngredient: "DIPIRONA MONOIDRATADA" },
    { productName: "DUOVAZI", activeIngredient: "DIOSMINA + HESPERIDINA" },
    { productName: "ECTRIN", activeIngredient: "PERMETRINA" },
    { productName: "Efexor", activeIngredient: "CLORIDRATO DE VENLAFAXINA" },
    { productName: "Eliquis", activeIngredient: "APIXABANA" },
    { productName: "EMGALITY", activeIngredient: "GALCANEZUMABE" },
    { productName: "EMISTIN", activeIngredient: "ACETATO DE DEXAMETASONA + DEXAMETASONA + FUMARATO DE CLEMASTINA" },
    { productName: "EMLA", activeIngredient: "LIDOCAÍNA + PRILOCAÍNA" },
    { productName: "ESPRAN", activeIngredient: "OXALATO DE ESCITALOPRAM" },
    { productName: "FEMINIQUE 30", activeIngredient: "DROSPIRENONA + ETINILESTRADIOL" },
    { productName: "FINIFERT", activeIngredient: "ENANTATO DE NORETISTERONA + VALERATO DE ESTRADIOL" },
    { productName: "FLUITOSS", activeIngredient: "CARBOCISTEÍNA" },
    { productName: "Frontal", activeIngredient: "ALPRAZOLAM" },
    { productName: "Glifage", activeIngredient: "CLORIDRATO DE METFORMINA" },
    { productName: "GLICOSE", activeIngredient: "GLICOSE ANIDRA" },
    { productName: "Haldol", activeIngredient: "HALOPERIDOL" },
    { productName: "HARTERYA", activeIngredient: "APIXABANA" },
    { productName: "HARVONI", activeIngredient: "LEDIPASVIR + SOFOSBUVIR" },
    { productName: "Hidroclorotiazida", activeIngredient: "HIDROCLOROTIAZIDA" },
    { productName: "ICADEN", activeIngredient: "ISOCONAZOL + NITRATO DE ISOCONAZOL" },
    { productName: "ICCOR", activeIngredient: "HEMIFUMARATO DE BISOPROLOL" },
    { productName: "JAYDESS", activeIngredient: "LEVONORGESTREL" },
    { productName: "JEMPERLI", activeIngredient: "DOSTARLIMABE" },
    { productName: "KEPPRA", activeIngredient: "LEVETIRACETAM" },
    { productName: "KIVEXA", activeIngredient: "LAMIVUDINA + SULFATO DE ABACAVIR" },
    { productName: "Lamictal", activeIngredient: "LAMOTRIGINA" },
    { productName: "LAVITAN", activeIngredient: "CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA + COLECALCIFEROL + L-LISINA + NICOTINAMIDA + PANTOTENATO DE CALCIO + RETINOL + RIBOFLAVINA + SULFATO DE MAGNÉSIO + SULFATO DE MANGANÊS + SULFATO DE ZINCO + SULFATO FERROSO + TREONINA + TRIPTOFANO + ÁCIDO ASCÓRBICO" },
    { productName: "Lexapro", activeIngredient: "OXALATO DE ESCITALOPRAM" },
    { productName: "LISTRIL", activeIngredient: "LISINOPRIL" },
    { productName: "LITANE", activeIngredient: "PELARGONIUM SIDOIDES DC." },
    { productName: "LITFULO", activeIngredient: "TOSILATO DE RITLECITINIBE" },
    { productName: "Lorax", activeIngredient: "LORAZEPAM" },
    { productName: "Losartana Potássica", activeIngredient: "LOSARTANA POTÁSSICA" },
    { productName: "LUMIDERM", activeIngredient: "HIDROQUINONA" },
    { productName: "LUMIGAN", activeIngredient: "BIMATOPROSTA" },
    { productName: "LYDIAN", activeIngredient: "ACETATO DE CIPROTERONA + ETINILESTRADIOL" },
    { productName: "LYLLAS", activeIngredient: "DROSPIRENONA + ETINILESTRADIOL" },
    { productName: "LYMPHOMYOSOT", activeIngredient: "ARANEUS DIADEMATUS + CALCIUM PHOSPHORICUM + EQUISETUM HYEMALE + FERRUM IODATUM + FUMARIA OFFICINALIS L. + GERANIUM ROBERTIANUM + GENTIANA LUTEA + JUGLANS REGIA L. + LEVOTHYROXINUM + MYOSIS ARVENSIS + NASTURTIUM OFFICINALE R.BR. + NATRUM SULFURICUM + PINUS SYLVESTRIS + SCROPHULARIA NODOSA + SMILAX OFFICINALIS + TEUCRIUM SCORODONIA + VERONICA OFFICINALIS" },
    { productName: "LYSTATE", activeIngredient: "ORLISTATE" },
    { productName: "LYSUGI", activeIngredient: "PREGABALINA" },
    { productName: "LYUMJEV", activeIngredient: "INSULINA LISPRO" },
    { productName: "MAFUSA", activeIngredient: "CLORIDRATO DE VALGANCICLOVIR" },
    { productName: "MATERSUPRE", activeIngredient: "ACETATO DE RETINOL + ACETATO DE TOCOFEROL + BIOTINA + CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + COLECALCIFEROL + FOSFATO DICÁLCICO + FUMARATO FERROSO + MONONITRATO DE TIAMINA + NICOTINAMIDA + PANTOTENATO DE CÁLCIO + RIBOFLAVINA + SULFATO DE MANGANÊS + ÁCIDO ASCÓRBICO + ÁCIDO FÓLICO + ÓXIDO DE COBRE + ÓXIDO DE MAGNÉSIO + ÓXIDO DE ZINCO" },
    { productName: "MATURE", activeIngredient: "ACETATO DE RACEALFATOCOFEROL + ACETATO DE RETINOL + BIOTINA + CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + COLECALCIFEROL + FERRO + FLUORETO + IODO + MANGANÊS + NICOTINAMIDA + NITRATO DE TIAMINA + PANAX GINSENG + PANTOTENATO DE CÁLCIO + POTÁSSIO + RIBOFLAVINA + RUTOSÍDEO + ÁCIDO ASCÓRBICO" },
    { productName: "MAVENCLAD", activeIngredient: "CLADRIBINA" },
    { productName: "MEGALOTECT", activeIngredient: "IMUNOGLOBULINA ANTICITOMEGALOVÍRUS" },
    { productName: "MENOEX", activeIngredient: "ACTAEA RACEMOSA + LACHESIS MUTUS + PULSATILLA NIGRICANS + SANGUINARIA CANADENSIS L. + SÉPIA SUCCUS + VALERIANA OFFICINALIS L." },
    { productName: "MINEROVIT", activeIngredient: "ACETATO de DEXTROALFATOCOFEROL + BIOTINA + BORO + CARBONATO DE CÁLCIO + CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + COLECALCIFEROL + FUMARATO FERROSO + NICOTINAMIDA + NITRATO DE TIAMINA + PALMITATO DE RETINOL + PANTOTENATO DE CALCIO + RIBOFLAVINA + SULFATO DE MANGANÊS + FOSFATO DE CÁLCIO DIBÁSICO DI-HIDRATADO + MOLIBDATO DE SÓDIO DIIDRATADO + ÁCIDO ASCÓRBICO" },
    { productName: "MINUSORB", activeIngredient: "ALENDRONATO DE SÓDIO" },
    { productName: "MIORRELAX", activeIngredient: "DIPIRONA MONOIDRATADA + CITRATO DE ORFENADRina + CAFEÍNA ANIDRA" },
    { productName: "Morfina", activeIngredient: "SULFATO DE MORFINA" },
    { productName: "MOTIX", activeIngredient: "ARNICA MONTANA L. + CALENDULA OFFICINALIS L. + HAMAMELIS VIRGINIANA L. + ECHINACEA ANGUSTIFOLIA DC. + ECHINACEA PURPUREA (L.) MOENCH + MATRICARIA CHAMOMILLA L. + BELLIS PERENNIS + SYMPHYTUM OFFICINALE + HYPERICUM PERFORATUM + ACHILLEA MILLEFOLIUM L. + ACONITUM NAPELLUS + ATROPA BELLADONNA + MERCURIUS SOLUBILIS + HEPAR SULPHUR + HEPAR SULFURIS" },
    { productName: "NIKI", activeIngredient: "DROSPIRENONA + ETINILESTRADIOL" },
    { productName: "nistatina", activeIngredient: "NISTATINA" },
    { productName: "NOVALGINA", activeIngredient: "DIPIRONA MONOIDRATADA" },
    { productName: "NUSIRA", activeIngredient: "CLORIDRATO DE TRAMADOL + DICLOFENACO SÓDICO" },
    { productName: "OLMECOR HCT", activeIngredient: "OLMESARTANA MEDOXOMILA + HIDROCLOROTIAZIDA" },
    { productName: "Omeprazol", activeIngredient: "OMEPRAZOL" },
    { productName: "Orkambi", activeIngredient: "IVACAFTOR + LUMACAFTOR" },
    { productName: "Otezla", activeIngredient: "APREMILASTE" },
    { productName: "PAINLIDA", activeIngredient: "CAFEÍNA ANIDRA + CARISOPRODOL + DICLOFENACO SÓDICO + PARACETAMOL" },
    { productName: "Pantoprazol", activeIngredient: "PANTOPRAZOL SÓDICO SESQUI-HIDRATADO" },
    { productName: "Plavix", activeIngredient: "BISSULFATO DE CLOPIDOGREL" },
    { productName: "POLIGNUTRI", activeIngredient: "CLORETO CRÔMICO HEXAIDRATADO + SULFATO CÚPRICO PENTAIDRATADO + SULFATO DE MANGANÊS MONOIDRATADO + SULFATO DE ZINCO HEPTAIDRATADO + ÁCIDO SELENIOSO" },
    { productName: "Pondera", activeIngredient: "CLORIDRATO DE PAROXETINA" },
    { productName: "PRALÍVIO", activeIngredient: "IBUPROFENO" },
    { productName: "PREDSIM", activeIngredient: "PREDNISONA" },
    { productName: "Priorix Tetra", activeIngredient: "VÍRUS DA VARICELA + VÍRUS DA CAXUMBA + VÍRUS DA RUBEOLA + VÍRUS DO SARAMPO" },
    { productName: "Pristiq", activeIngredient: "SUCCINATO DE DESVENLAFAXINA MONOIDRATADO" },
    { productName: "Prolastin-C", activeIngredient: "ALFA1ANTITRIPSINA" },
    { productName: "Prozac", activeIngredient: "CLORIDRATO DE FLUOXETINA" },
    { productName: "PULNAR", activeIngredient: "ACETILCISTEÍNA" },
    { productName: "Puran T4", activeIngredient: "LEVOTIROXINA SÓDICA" },
    { productName: "QLAIRA", activeIngredient: "DIENOGESTE + VALERATO DE ESTRADIOL" },
    { productName: "QTERN", activeIngredient: "CLORIDRATO DE SAXAGLIPTINA DI-HIDRATADA + PROPILENOGLICOLATO DE DAPAGLIFLOZINA MONOIDRATADO" },
    { productName: "QUEROPAX", activeIngredient: "HEMIFUMARATO DE QUETIAPINA" },
    { productName: "QUESTRAN LIGHT", activeIngredient: "COLESTIRAMINA" },
    { productName: "RANIVISIO", activeIngredient: "RANIBIZUMAB" },
    { productName: "REACBE", activeIngredient: "LORATADINA" },
    { productName: "RECAPSER", activeIngredient: "CLORIDRATO DE SERTRALINA" },
    { productName: "REGULADOR XAVIER N°1", activeIngredient: "CLORETO DE CÁLCIO + EXTRATO FLUIDO + TINTURA DE ATROPA BELADONA" },
    { productName: "Remsima", activeIngredient: "INFLIXIMABE" },
    { productName: "rifamicina", activeIngredient: "RIFAMICINA" },
    { productName: "Risperdal", activeIngredient: "RISPERIDONA" },
    { productName: "risperidona", activeIngredient: "RISPERIDONA" },
    { productName: "Rivotril", activeIngredient: "CLONAZEPAM" },
    { productName: "Rocefin", activeIngredient: "CEFTRIAXONA DISSÓDICA" },
    { productName: "ROZEX", activeIngredient: "METRONIDAZOL" },
    { productName: "ROZUBINE", activeIngredient: "ROSUVASTATINA CÁLCICA" },
    { productName: "RPHKARDIA", activeIngredient: "TETRAFLUORBORATO TETRAMIBI CUPROSO" },
    { productName: "RYVYRY", activeIngredient: "RIVAROXABANA" },
    { productName: "Salonpas Adesivo", activeIngredient: "CÂNFORA + LEVOMENTOL + SALICILATO DE METILA" },
    { productName: "SAMAR-IPEN", activeIngredient: "SAMÁRIO 153SM LEXIDRONAM" },
    { productName: "SAMILE", activeIngredient: "SUCCINATO DE SOLIFENACINA" },
    { productName: "SANTISAVIT C", activeIngredient: "ÁCIDO ASCÓRBICO" },
    { productName: "SAUMYA", activeIngredient: "MESILATO DE LENVATINIBE" },
    { productName: "SEIZLA", activeIngredient: "LACOSAMIDA" },
    { productName: "SEKI", activeIngredient: "FENDIZOATO DE CLOPERASTINA" },
    { productName: "Selozok", activeIngredient: "SUCCINATO DE METOPROLOL" },
    { productName: "SEMGLEE", activeIngredient: "INSULINA GLARGINA" },
    { productName: "Seroquel", activeIngredient: "HEMIFUMARATO DE QUETIAPINA" },
    { productName: "Sinvastatina", activeIngredient: "SINVASTATINA" },
    { productName: "SMOFKABIVEN LIVRE DE ELETRÓLITOS", activeIngredient: "ACETATO DE LISINA + ALANINA + ARGININA + FENILALANINA + GLICINA + GLICOSE MONOHIDRATADA + HISTIDINA + ISOLEUCINA + LEUCINA + LEVOVALINA + PROLINA + SERINA + TAURINA + TIROSINA + TREONINA + TRIGLICERÍDEOS CADEIA MÉDIA + TRIPTOFANO + METIONINA (11 C) + ÓLEO DE OLIVA + ÓLEO DE PEIXE + ÓLEO DE SOJA" },
    { productName: "SONDELBAY", activeIngredient: "TERIPARATIDA" },
    { productName: "SPASCUPREEL", activeIngredient: "ACONITUM NAPELLUS + AMMONIUM BROMATUM + AGARICUS MUSCARIUS + CHAMOMILLA RECUTITA + CITRULLUS COLOCYNTHIS SCHRAD. + COLOCYNTHIS + GELSEMIUM SEMPERVIRENS + MAGNESIUM PHOSPHORICUM + MATRICARIA RECUTITA L. + PASSIFLORA INCARNATA + VERATRUM ALBUM + ATROPINUM SULFURICUM + CUPRUM SULFURICUM" },
    { productName: "Spikevax", activeIngredient: "VACINA COVID-19" },
    { productName: "STOMVYC", activeIngredient: "BICARBONATO DE SÓDIO + CARBONATO DE SÓDIO" },
    { productName: "TANDRILAX", activeIngredient: "CARISOPRODOL + DICLOFENACO DE SÓDIO + PARACETAMOL + CAFEÍNA" },
    { productName: "Tegretol", activeIngredient: "CARBAMAZEPINA" },
    { productName: "TIOXIN", activeIngredient: "CLAVULANATO DE POTÁSSIO + TICARCILINA DISSÓDICA" },
    { productName: "TORVILIP", activeIngredient: "ATORVASTATINA CÁLCICA" },
    { productName: "Tramal", activeIngredient: "CLORIDRATO DE TRAMADOL" },
    { productName: "TUA D3", activeIngredient: "COLECALCIFEROL" },
    { productName: "Tylenol", activeIngredient: "PARACETAMOL" },
    { productName: "VERASEAL", activeIngredient: "FIBRINOGÊNIO + TROMBINA" },
    { productName: "VEXICA", activeIngredient: "SUCCINATO DE SOLIFENACINA" },
    { productName: "VITALIA", activeIngredient: "DICLORIDRATO DE BETAISTINA" },
    { productName: "VITPEEL", activeIngredient: "TRETINOÍNA" },
    { productName: "VOYDEYA", activeIngredient: "DANICOPANE" },
    { productName: "VPRIV", activeIngredient: "ALFAVELAGLICERASE" },
    { productName: "VSIQQ", activeIngredient: "BROLUCIZUMABE" },
    { productName: "VYLOY", activeIngredient: "ZOLBETUXIMABE" },
    { productName: "VYXARA", activeIngredient: "SUCCINATO DE DESVENLAFAXINA MONOIDRATADO" },
    { productName: "WELETUSS", activeIngredient: "BRYONIA ALBA L. + CUPRUM ACETICUM + DROSERA ROTUNDIFOLIA + CEPHAELIS IPECACUANHA" },
    { productName: "WELLBUTRIN", activeIngredient: "CLORIDRATO DE BUPROPIONA" },
    { productName: "Wellbutrin XL", activeIngredient: "CLORIDRATO DE BUPROPIONA" },
    { productName: "Xarelto", activeIngredient: "RIVAROXABANA" },
    { productName: "ZEEL COMP N", activeIngredient: "RHUS TOXICODENDRON L. + SANGUINARIA CANADENSIS L. + SOLANUM DULCAMARA L. + SULFUR + ARNICA MONTANA" },
    { productName: "ZELAZAFER", activeIngredient: "SACARATO DE ÓXIDO FÉRRICO" },
    { productName: "ZIMIEX DUO", activeIngredient: "EZETIMIBA + ROSUVASTATINA CÁLCICA" },
    { productName: "Zoloft", activeIngredient: "CLORIDRATO DE SERTRALINA" },
    { productName: "ZOTEON PÓ", activeIngredient: "TOBRAMICINA" },
    { productName: "ZOUP SL", activeIngredient: "HEMITARTARATO DE ZOLPIDEM" },
    { productName: "Zyprexa", activeIngredient: "OLANZAPINA" },
    { productName: "acetato de dexametasona", activeIngredient: "ACETATO DE DEXAMETASONA" },
    { productName: "acetato de icatibanto", activeIngredient: "ACETATO DE ICATIBANTO" },
    { productName: "aciclovir", activeIngredient: "ACICLOVIR" }
];
